AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'config/*.rb'
    - 'config/initializers/*.rb'
    - 'config/environments/*.rb'
    - 'bin/*/'

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
